/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#3a3939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#b9ccb2',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        outline: '#84967e',
        'outline-variant': '#3b4b37',
        'surface-tint': '#00e639',
        primary: '#ebffe2',
        'on-primary': '#003907',
        'primary-container': '#00ff41',
        'on-primary-container': '#007117',
        'inverse-primary': '#006e16',
        secondary: '#ffd393',
        'on-secondary': '#432c00',
        'secondary-container': '#fdaf00',
        'on-secondary-container': '#694600',
        tertiary: '#fff7f6',
        'on-tertiary': '#690100',
        'tertiary-container': '#ffd2cb',
        'on-tertiary-container': '#c40100',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#72ff70',
        'primary-fixed-dim': '#00e639',
        'on-primary-fixed': '#002203',
        'on-primary-fixed-variant': '#00530e',
        'secondary-fixed': '#ffddaf',
        'secondary-fixed-dim': '#ffba43',
        'on-secondary-fixed': '#281800',
        'on-secondary-fixed-variant': '#614000',
        'tertiary-fixed': '#ffdad4',
        'tertiary-fixed-dim': '#ffb4a8',
        'on-tertiary-fixed': '#410000',
        'on-tertiary-fixed-variant': '#930100',
        background: '#131313',
        'on-background': '#e5e2e1',
        'surface-variant': '#353534',
      },
      spacing: {
        'margin-desktop': '32px',
        unit: '4px',
        gutter: '16px',
        'margin-mobile': '16px',
        'border-thick': '2px',
        'border-thin': '1px',
      },
      fontFamily: {
        'headline-lg': ['JetBrains Mono', 'monospace'],
        'body-lg': ['JetBrains Mono', 'monospace'],
        'body-md': ['JetBrains Mono', 'monospace'],
        'headline-lg-mobile': ['JetBrains Mono', 'monospace'],
        'code-sm': ['JetBrains Mono', 'monospace'],
        'headline-md': ['JetBrains Mono', 'monospace'],
        'label-caps': ['Space Mono', 'monospace'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'code-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};
